name: Unit Test

on:
  push:
    branches: [ main ]  # Adjust branch(es) to trigger on push

jobs:
  test:
    runs-on: ubuntu-latest  # Adjust OS if needed (e.g., ubuntu-20.04)
    steps:
      - uses: actions/checkout@v3  # Checkout code from repository
      - name: Install dependencies (if needed, adjust commands)
        run: |
          python -m pip install librosa matplotlib seaborn  # Assuming you use librosa for audio processing
      - name: Run unit tests
        run: |
          python test_data_challenge.py  # Adjust path if needed